<?php

$title = 'All Toppings';
$this->headTitle($title);

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div class="alert-success">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');


echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('topping', array('action'=>'add'));?>">Add New Topping</a>
</p>
<?php
echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));
?>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
    </tr>
    <?php foreach ($toppings as $topping) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($topping->id);?></td>
            <td><?php echo $this->escapeHtml($topping->name);?></td>
        </tr>
    <?php endforeach; ?>
</table>