<?php

$title = 'All Pizzas';
$this->headTitle($title);

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div class="alert-success">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');


echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('pizza', array('action'=>'add'));?>">Add New Pizza</a>
</p>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($pizzas as $pizza) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($pizza->name);?></td>
            <td><?php echo $this->escapeHtml($pizza->description);?></td>
            <td>
                <a href="<?php echo $this->url('pizza',
                    array('action'=>'edit', 'id' => $pizza->id));?>">View / Add Toppings</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>